name: Update Notion README

on:
  push:
    paths:
      - "README.md"

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 최신 버전 사용

      - name: Get README Content
        id: readme
        run: |
          # README.md 파일의 내용을 안전하게 JSON 형식으로 변환
          README_CONTENT=$(cat README.md | jq -Rs .)  # jq를 사용하여 JSON 형식으로 변환
          echo "content=$README_CONTENT" >> $GITHUB_ENV  # 환경 파일에 변수 저장

      - name: Update Notion Page
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: 13b776dbad2a804c8b6cdf5255f3039d
          README_CONTENT: ${{ env.content }}  # 환경 파일에서 읽어옴
        run: |
          curl -v -X PATCH "https://api.notion.com/v1/blocks/$NOTION_PAGE_ID/children" \
          -H "Authorization: Bearer $NOTION_API_KEY" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "children": [
              {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                  "rich_text": [
                    {
                      "type": "text",
                      "text": {
                        "content": '"$README_CONTENT"'
                      }
                    }
                  ]
                }
              }
            ]
          }'
