name: Update Notion README

on:
  push:
    paths:
      - "README.md"

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get README Content
        id: readme
        run: |
          export README_CONTENT=$(cat README.md)
          echo "::set-output name=content::$README_CONTENT"

      - name: Update Notion Page
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}   # GitHub Secrets에서 API 키를 가져옵니다.
          NOTION_PAGE_ID: 13b776dbad2a804c8b6cdf5255f3039d
        run: |
          curl -X PATCH "https://api.notion.com/v1/blocks/$NOTION_PAGE_ID/children" \
          -H "Authorization: Bearer $NOTION_API_KEY" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "children": [
              {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                  "text": [
                    {
                      "type": "text",
                      "text": {
                        "content": "'"$README_CONTENT"'"
                      }
                    }
                  ]
                }
              }
            ]
          }'
