name: Update Notion README

on:
  push:
    paths:
      - "README.md"

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 최신 버전 사용

      - name: Get README Content
        id: readme
        run: |
          # README.md 파일의 내용을 읽고 직접 변수에 저장
          README_CONTENT=$(cat README.md)
          # 파일의 내용을 2000자 이하로 분할하여 JSON 형식에 맞게 준비
          CONTENT_LENGTH=${#README_CONTENT}
          MAX_LENGTH=2000
          START_INDEX=0
          END_INDEX=$MAX_LENGTH
          BLOCKS=""

          while [ $START_INDEX -lt $CONTENT_LENGTH ]; do
            # 텍스트 자르기 (최대 2000자)
            PART="${README_CONTENT:$START_INDEX:$MAX_LENGTH}"

            # 만약 자른 부분이 2000자를 초과하면 강제로 잘라서 2000자 이하로 설정
            if [ ${#PART} -gt $MAX_LENGTH ]; then
              PART="${PART:0:$MAX_LENGTH}"
            fi

            # JSON 포맷에 맞게 블록을 추가
            BLOCKS="$BLOCKS
            {
              \"object\": \"block\",
              \"type\": \"paragraph\",
              \"paragraph\": {
                \"rich_text\": [
                  {
                    \"type\": \"text\",
                    \"text\": {
                      \"content\": \"$PART\"
                    }
                  }
                ]
              }
            }"
            
            # 블록 구분을 위한 쉼표 추가
            if [ $START_INDEX -lt $((CONTENT_LENGTH - MAX_LENGTH)) ]; then
              BLOCKS="$BLOCKS,"
            fi

            START_INDEX=$END_INDEX
            END_INDEX=$((END_INDEX + MAX_LENGTH))
          done

          # Notion API 요청 보내기
          curl -v -X PATCH "https://api.notion.com/v1/blocks/${{ secrets.NOTION_PAGE_ID }}/children" \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data "{
            \"children\": [$BLOCKS]
          }"
